/* Generated by AN DISI Unibo */ 
package it.unibo.ctxoutsonar
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "outsonar", this, "systembusinesslogic.pl", "sysRules.pl"
	)
}

