/* Generated by AN DISI Unibo */ 
package it.unibo.dtoccupiedwatchdog

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Dtoccupiedwatchdog ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "init"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						println("[dtoccupiedwatchdog] | [State] init | Entry point.")
						println("[dtoccupiedwatchdog] | [State] init | Exit point.")
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
						println("[dtoccupiedwatchdog] | [State] wait | Entry point.")
						println("[dtoccupiedwatchdog] | [State] wait | Exit point.")
					}
					 transition(edgeName="t013",targetState="running",cond=whenDispatch("start_watchdog"))
					transition(edgeName="t014",targetState="wait",cond=whenDispatch("stop_watchdog"))
				}	 
				state("running") { //this:State
					action { //it:State
						println("[dtoccupiedwatchdog] | [State] running | Entry point.")
						println("[dtoccupiedwatchdog] | [State] running | Exit point.")
						stateTimer = TimerActor("timer_running", 
							scope, context!!, "local_tout_dtoccupiedwatchdog_running", 60000.toLong() )
					}
					 transition(edgeName="t015",targetState="emitTimeout",cond=whenTimeout("local_tout_dtoccupiedwatchdog_running"))   
					transition(edgeName="t016",targetState="wait",cond=whenDispatch("stop_watchdog"))
				}	 
				state("emitTimeout") { //this:State
					action { //it:State
						println("[dtoccupiedwatchdog] | [State] emitTimeout | Entry point.")
						emit("local_timeout", "local_timeout(X)" ) 
						println("[dtoccupiedwatchdog] | [State] emitTimeout | Exit point.")
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
}
