/* Generated by AN DISI Unibo */ 
package it.unibo.physicalweightsensor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Physicalweightsensor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "init"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						println("[physicalweightsensor] | [State] init | Entry point.")
						if( checkMsgContent( Term.createTerm("setup(X)"), Term.createTerm("setup(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("[physicalweightsensor] | [State] init | Setup.")
								answer("setup", "done", "done(X)"   )  
						}
						updateResourceRep( "weight(0.0)"  
						)
						println("[physicalweightsensor] | [State] init | Exit point.")
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
						println("[physicalweightsensor] | [State] wait | Entry point.")
						if( checkMsgContent( Term.createTerm("input_weight(W)"), Term.createTerm("input_weight(W)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val W = payloadArg(0).toFloat()  
								emit("weight", "weight($W)" ) 
								updateResourceRep( "weight($W)"  
								)
						}
						println("[physicalweightsensor] | [State] wait | Exit point.")
					}
					 transition(edgeName="t00",targetState="wait",cond=whenDispatch("input_weight"))
					transition(edgeName="t01",targetState="init",cond=whenRequest("setup"))
				}	 
			}
		}
}
