/* Generated by AN DISI Unibo */ 
package it.unibo.ctxfan
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "fan", this, "systemthermometer.pl", "sysRules.pl"
	)
}

